var Massage = {
    MSG : "you have entered the darksite, although we will not collect static data and other information about visitors, but we can not guarantee 100% safe",
    showWarning: function(){
        alert(`Attantions: ${this.MSG}`);
    }
};
	Massage.showWarning();

function Found () {
	'Vm0weE1GVXhUWGxUYms1cFRUSjRXRmxyWkc5VlZscHlWbTFHVkUxV1duaFZiVFZyVkcxS1NWRnJhRmhYU0VKSVdWVlZlRk5IVmtaalJtUlhaV3RGZUZkV1ZtRmhNVXB5VFZab1QxWnVRbTlaVkVvd1RrWmtXR1JHWkdwTlZUVklWakkxVTFWR1duSlhiazVYWWtaYU1scFZXbXRXTVdSMFpFWldUbUV6UWtoWGJGWlhWVEZXZEZOdVNsUmlWMmhoVm0xNFlWTXhVbGRYYms1cVZteEtlbFl5TVVkVWJVcEdWMVJHVjFaNlFYaFdha3BHWlVaS1dWcEdVbGhTTVVwb1YxY3dlRTVHU2tkaVJtUllZbTFTV0ZWdGRHRk5SbXhXVm01a1YxSnJjRmRaTUdoaFYwWmFSbUV6YUZkV00yZ3lXbFphVDFkWFNrZGhSbVJPWWtWd05WWnNaSGRUTWtsNVZWaG9hRTB6UW5CVmJGVXhZakZXZEU1VlRrNVNiR3cxVkd4V1QyRkdXbkppUkZaaFZsZE5NVmRXV2t0WFJsWnpXa1p3YkdFd2NEWldWRUpoVlRKU1YxcElVbWxTYlZKUFZtMTRkMDFXV1hsa1JtUm9ZWHBXU0ZscVRtdFViRnB6VjIwNVZWWkZXbWhXVlZwM1YwZE5lbHBIZUdsU2EzQllWbXhrZWsxV1VuUlNhbHBUWW0xU2FGVnJWVEZXUmxwRlUyeGthbUpWY0VaVmJYaFhWakF3ZDFOclVsZFNiVkkyVkZaVk1XTXhjRWRXYkZwb1pXeGFXRlpHVmxka01sSnpXa1pvVGxOSGFGZFphMk0xVGtacmQyRkdUbWhXYXpWSVZqSXhiMVpzV2taVGEzUmhVa1ZhZWxadGVIZFNNV1IwVW1zMVYwMHhSWGhXYkdOM1RWZFJlVkpZYUZSWFNFSnZWVEJWZDA5UlBUMD0='
}

